
# Nombre del workflow o pipeline 

name: CI Practica 

# Trigger que permite que el worflow se ejecute 
# En este caso el trigger se ejecuta cada vez que 
# se realice push en la rama main

on:
  push: 
    branches: 
      - main

# Son las tareas que el workflow va a realizar 
# Siempre se deben declarar jobs para que el workflow 
# pueda trabajar 

jobs: 
  build:
    #Entorno en el cual va a trabajar el workflow 
    runs-on: ubuntu-latest

    # Pasos para ejecutar el workflow 
    steps:
        # Accion que permite clonar el repo 
      - name: Checkout 
        uses: actions/checkout@v4

        # Accion que permite instalar node en ubuntu
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '18'

        # Comando que permite instalar dependencias necesarias
        # para compilar el proyecto 
      - name: Install dependencies
        run: npm install
      
        # Comando para probar el proyecto
        # Ejecucion de pruebas unitarias 
      - name: Run tests
        run: npm run test

        # Comando para construir la pagina estatica
      - name: Build page 
        run: npm run build

        # Accion que permite subir la carpeta public como artifact 
      - name: Upload artifact 
        uses: actions/upload-page-artifact@v3
        with:
          path: public/
    
    # Job deploy que depende del build para ejecutarse 
    deploy:
      runs-on: ubuntu-latest
      needs: build
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      # Configuracion de permisos para el despliegue de la aplcacion
      permissions:
        pages: write 
        id-token: write
      
      # Definicion de un entorno para rastrear la url de despliegue 
      environment: 
        name: github-pages
        url: ${{ steps.deployment.outuputs.page_url }}

      # Usamos la accion para publicar la pagina en GitHub Pages
      steps:
        - name: Deploy to GitHub pages
          id: deployment
          uses: actions/deploy-pages@v4

      



